CREATE VIEW [TimeManagement].[VI_Projects]
	AS SELECT  [Projects].[PK_Id]
	  ,[Projects].[Name]
	  ,[FK_OrderNumber]
	  ,[TimeEstimation]
	  ,[FK_ProjectLeader]
	  ,[NK_Name] as [UserName]
	  ,[Scope]
	  ,[Number] as [OrderName]
	  ,[FK_TimeType]
	  ,[TimeType].[Name] as [TimeTypeName]
	  ,COALESCE(SUM([TimeManagement].[TimeRegistration].[Time]),0) as [timeSum]
  FROM [Projects]
  JOIN [Users] ON [Projects].[FK_ProjectLeader] = [Users].[PK_Id]
  JOIN [OrderNumber] ON [Projects].[FK_OrderNumber] = [OrderNumber].[PK_Id]
  LEFT JOIN [TimeType] ON [Projects].[FK_TimeType] = [TimeType].[PK_Id]
  LEFT JOIN [TimeManagement].[TimeRegistration] ON [TimeManagement].[Projects].[PK_Id] = [TimeRegistration].[FK_ProjectId]
  GROUP BY [Projects].[PK_Id]
	  ,[Projects].[Name]
	  ,[FK_OrderNumber]
	  ,[TimeEstimation]
	  ,[FK_ProjectLeader]
	  ,[NK_Name]
	  ,[Scope]
	  ,[Number]
	  ,[FK_TimeType]
	  ,[TimeType].[Name]
