CREATE VIEW [TimeManagement].[VI_Projects]
	AS SELECT DISTINCT  [Projects].[PK_Id]
	  ,[Projects].[Name]
	  ,[FK_OrderNumber]
	  ,[TimeEstimation]
	  ,[FK_ProjectLeader]
	  ,[NK_Name] as [UserName]
	  ,[Scope]
	  ,[Number] as [OrderName]
	  ,[FK_TimeType]
	  ,[TimeType].[Name] as [TimeTypeName]
	  ,[Projects].[SiteOrVersion]
	  ,[FK_Country]
	  ,[Country].[CountryName] as [CountryName]
	  ,[FK_PlatformOrProduct]
	  ,[PlatformOrProduct].[ProductName] as [PlatformOrProductName]
	  ,[FK_Turbine]
	  ,[Turbine].[TurbineName]
	  ,[ProjectComment]
	  ,COALESCE(SUM([TimeManagement].[TimeRegistration].[Time]),0) as [timeSum]
  FROM [Projects]
  JOIN [Users] ON [Projects].[FK_ProjectLeader] = [Users].[PK_Id]
  JOIN [OrderNumber] ON [Projects].[FK_OrderNumber] = [OrderNumber].[PK_Id]
  LEFT JOIN [TimeType] ON [Projects].[FK_TimeType] = [TimeType].[PK_Id]
  LEFT JOIN [TimeManagement].[TimeRegistration] ON [TimeManagement].[Projects].[PK_Id] = [TimeRegistration].[FK_ProjectId]
  JOIN [Country] ON [Projects].[FK_Country] = [Country].[PK_Id]
  JOIN [PlatformOrProduct] ON [Projects].[FK_PlatformOrProduct] = [PlatformOrProduct].[PK_Id]
  JOIN [Turbine] ON [Projects].[FK_Turbine] = [Turbine].[PK_Id]
  Group By
  [Projects].[PK_Id],[Projects].[Name]
	  ,[FK_OrderNumber]
	  ,[TimeEstimation]
	  ,[FK_ProjectLeader]
	  ,[NK_Name]
	  ,[Scope]
	  ,[Number]
	  ,[FK_TimeType]
	  ,[TimeType].[Name]
	  ,[SiteOrVersion]
	  ,[FK_Country]
	  ,[CountryName]
	  ,[FK_PlatformOrProduct]
	  ,[PlatformOrProduct].[ProductName]
	  ,[FK_Turbine]
	  ,[Turbine].[TurbineName]
	  ,[ProjectComment]

