GRANT CONNECT TO [AD009\RA201_TMDBTIMEMANAGEMENT_ADMINISTRATOR_L];
GO
GRANT DELETE ON SCHEMA::[TimeManagement] TO [AD009\RA201_TMDBTIMEMANAGEMENT_ADMINISTRATOR_L]
GO
GRANT EXECUTE ON SCHEMA::[TimeManagement] TO [AD009\RA201_TMDBTIMEMANAGEMENT_ADMINISTRATOR_L]
GO
GRANT INSERT ON SCHEMA::[TimeManagement] TO [AD009\RA201_TMDBTIMEMANAGEMENT_ADMINISTRATOR_L]
GO
GRANT SELECT ON SCHEMA::[TimeManagement] TO [AD009\RA201_TMDBTIMEMANAGEMENT_ADMINISTRATOR_L]
GO
GRANT UPDATE ON SCHEMA::[TimeManagement] TO [AD009\RA201_TMDBTIMEMANAGEMENT_ADMINISTRATOR_L]
GO

