GRANT CONNECT TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
--Intended Permissions below:
--Time Reg - "Insert", Execute, "Update"
--Comment - "Insert", Execute, "Update"
--User Assignement - ALL
--Union Page - "Insert", Execute
--User - Add New User "Insert"

--VIEWS ALL - SELECT

--Each segment will then have a comment with what the segment is suppouse to give permissions to.
--VIEWS ALL - SELECT
GO
GRANT SELECT ON [TimeManagement].[VI_CustomerRef] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT SELECT ON [TimeManagement].[VI_Requester] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT SELECT ON [TimeManagement].[VI_RequestOrg] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT SELECT ON [TimeManagement].[VI_Country] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT SELECT ON [TimeManagement].[VI_PlatformOrProduct] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT SELECT ON [TimeManagement].[VI_TaskType] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT SELECT ON [TimeManagement].[VI_TimeType] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT SELECT ON [TimeManagement].[VI_Turbine] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT SELECT ON [TimeManagement].[VI_Comments] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT SELECT ON [TimeManagement].[VI_OrderNumber] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT SELECT ON [TimeManagement].[VI_ProjectAndOrderTools] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT SELECT ON [TimeManagement].[VI_ProjectAndOrderToolsUnion] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT SELECT ON [TimeManagement].[VI_Projects] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT SELECT ON [TimeManagement].[VI_TimeRegistration] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT SELECT ON [TimeManagement].[VI_UserAssignment] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT SELECT ON [TimeManagement].[VI_Users] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT SELECT ON [TimeManagement].[VI_UserTimePerProject] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT SELECT ON [TimeManagement].[VI_TimePerOrdernumber] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO


--Time Reg - "Insert", "Update"
GRANT EXECUTE ON [TimeManagement].[SP_AddTimeRegistration] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT EXECUTE ON [TimeManagement].[SP_UpdateTimeRegistration] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
--Comment - "Insert",  "Update"
GRANT EXECUTE ON [TimeManagement].[SP_AddComment] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT EXECUTE ON [TimeManagement].[SP_UpdateComments] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
--User Assignement - ALL
GRANT EXECUTE ON [TimeManagement].[SP_UpdateUserAssignment] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT EXECUTE ON [TimeManagement].[SP_AddUserAssignment] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT EXECUTE ON [TimeManagement].[SP_RemoveUserAssignment] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO


--Union Page - "Insert", Execute
GRANT EXECUTE ON [TimeManagement].[SP_AddCustomerRef] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT EXECUTE ON [TimeManagement].[SP_AddRequester] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT EXECUTE ON [TimeManagement].[SP_AddRequestOrg] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT EXECUTE ON [TimeManagement].[SP_AddPlatformOrProduct] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT EXECUTE ON [TimeManagement].[SP_AddTaskType] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT EXECUTE ON [TimeManagement].[SP_AddTimeType] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
GRANT EXECUTE ON [TimeManagement].[SP_AddTurbine] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
GO
--User - "Insert"
GRANT EXECUTE ON [TimeManagement].[SP_AddNewUser] TO [AD009\RA201_TMDBTIMEMANAGEMENT_USER_L];
