

IF NOT EXISTS(SELECT TOP(1) [CountryName] FROM TimeManagement.Country)
BEGIN
DBCC CHECKIDENT ('[TimeManagement].[Country]', RESEED, 1) 
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'AF', 'Afghanistan');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'AL', 'Albania');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'DZ', 'Algeria');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'DS', 'American Samoa');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'AD', 'Andorra');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'AO', 'Angola');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'AI', 'Anguilla');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'AQ', 'Antarctica');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'AG', 'Antigua and Barbuda');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'AR', 'Argentina');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'AM', 'Armenia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'AW', 'Aruba');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'AU', 'Australia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'AT', 'Austria');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'AZ', 'Azerbaijan');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BS', 'Bahamas');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BH', 'Bahrain');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BD', 'Bangladesh');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BB', 'Barbados');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BY', 'Belarus');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BE', 'Belgium');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BZ', 'Belize');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BJ', 'Benin');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BM', 'Bermuda');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BT', 'Bhutan');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BO', 'Bolivia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BA', 'Bosnia and Herzegovina');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BW', 'Botswana');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BV', 'Bouvet Island');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BR', 'Brazil');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'IO', 'British Indian Ocean Territory');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BN', 'Brunei Darussalam');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BG', 'Bulgaria');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BF', 'Burkina Faso');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'BI', 'Burundi');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'KH', 'Cambodia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'CM', 'Cameroon');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'CA', 'Canada');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'CV', 'Cape Verde');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'KY', 'Cayman Islands');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'CF', 'Central African Republic');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'TD', 'Chad');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'CL', 'Chile');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'CN', 'China');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'CX', 'Christmas Island');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'CC', 'Cocos (Keeling) Islands');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'CO', 'Colombia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'KM', 'Comoros');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'CG', 'Congo');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'CK', 'Cook Islands');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'CR', 'Costa Rica');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'HR', 'Croatia (Hrvatska)');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'CU', 'Cuba');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'CY', 'Cyprus');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'CZ', 'Czech Republic');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'DK', 'Denmark');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'DJ', 'Djibouti');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'DM', 'Dominica');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'DO', 'Dominican Republic');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'TP', 'East Timor');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'EC', 'Ecuador');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'EG', 'Egypt');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SV', 'El Salvador');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GQ', 'Equatorial Guinea');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'ER', 'Eritrea');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'EE', 'Estonia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'ET', 'Ethiopia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'FK', 'Falkland Islands (Malvinas)');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'FO', 'Faroe Islands');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'FJ', 'Fiji');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'FI', 'Finland');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'FR', 'France');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'FX', 'France, Metropolitan');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GF', 'French Guiana');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'PF', 'French Polynesia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'TF', 'French Southern Territories');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GA', 'Gabon');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GM', 'Gambia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GE', 'Georgia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'DE', 'Germany');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GH', 'Ghana');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GI', 'Gibraltar');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GK', 'Guernsey');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GR', 'Greece');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GL', 'Greenland');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GD', 'Grenada');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GP', 'Guadeloupe');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GU', 'Guam');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GT', 'Guatemala');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GN', 'Guinea');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GW', 'Guinea-Bissau');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GY', 'Guyana');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'HT', 'Haiti');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'HM', 'Heard and Mc Donald Islands');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'HN', 'Honduras');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'HK', 'Hong Kong');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'HU', 'Hungary');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'IS', 'Iceland');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'IN', 'India');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'IM', 'Isle of Man');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'ID', 'Indonesia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'IR', 'Iran (Islamic Republic of)');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'IQ', 'Iraq');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'IE', 'Ireland');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'IL', 'Israel');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'IT', 'Italy');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'CI', 'Ivory Coast');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'JE', 'Jersey');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'JM', 'Jamaica');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'JP', 'Japan');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'JO', 'Jordan');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'KZ', 'Kazakhstan');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'KE', 'Kenya');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'KI', 'Kiribati');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'KP', 'Korea, Democratic People''s Republic of');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'KR', 'Korea, Republic of');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'XK', 'Kosovo');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'KW', 'Kuwait');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'KG', 'Kyrgyzstan');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'LA', 'Lao People''s Democratic Republic');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'LV', 'Latvia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'LB', 'Lebanon');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'LS', 'Lesotho');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'LR', 'Liberia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'LY', 'Libyan Arab Jamahiriya');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'LI', 'Liechtenstein');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'LT', 'Lithuania');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'LU', 'Luxembourg');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MO', 'Macau');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MK', 'Macedonia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MG', 'Madagascar');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MW', 'Malawi');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MY', 'Malaysia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MV', 'Maldives');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'ML', 'Mali');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MT', 'Malta');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MH', 'Marshall Islands');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MQ', 'Martinique');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MR', 'Mauritania');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MU', 'Mauritius');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'TY', 'Mayotte');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MX', 'Mexico');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'FM', 'Micronesia, Federated States of');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MD', 'Moldova, Republic of');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MC', 'Monaco');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MN', 'Mongolia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'ME', 'Montenegro');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MS', 'Montserrat');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MA', 'Morocco');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MZ', 'Mozambique');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MM', 'Myanmar');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'NA', 'Namibia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'NR', 'Nauru');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'NP', 'Nepal');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'NL', 'Netherlands');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'AN', 'Netherlands Antilles');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'NC', 'New Caledonia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'NZ', 'New Zealand');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'NI', 'Nicaragua');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'NE', 'Niger');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'NG', 'Nigeria');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'NU', 'Niue');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'NF', 'Norfolk Island');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'MP', 'Northern Mariana Islands');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'NO', 'Norway');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'OM', 'Oman');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'PK', 'Pakistan');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'PW', 'Palau');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'PS', 'Palestine');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'PA', 'Panama');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'PG', 'Papua New Guinea');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'PY', 'Paraguay');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'PE', 'Peru');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'PH', 'Philippines');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'PN', 'Pitcairn');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'PL', 'Poland');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'PT', 'Portugal');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'PR', 'Puerto Rico');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'QA', 'Qatar');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'RE', 'Reunion');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'RO', 'Romania');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'RU', 'Russian Federation');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'RW', 'Rwanda');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'KN', 'Saint Kitts and Nevis');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'LC', 'Saint Lucia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'VC', 'Saint Vincent and the Grenadines');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'WS', 'Samoa');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SM', 'San Marino');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'ST', 'Sao Tome and Principe');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SA', 'Saudi Arabia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SN', 'Senegal');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'RS', 'Serbia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SC', 'Seychelles');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SL', 'Sierra Leone');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SG', 'Singapore');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SK', 'Slovakia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SI', 'Slovenia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SB', 'Solomon Islands');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SO', 'Somalia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'ZA', 'South Africa');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GS', 'South Georgia South Sandwich Islands');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SS', 'South Sudan');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'ES', 'Spain');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'LK', 'Sri Lanka');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SH', 'St. Helena');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'PM', 'St. Pierre and Miquelon');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SD', 'Sudan');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SR', 'Suriname');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SJ', 'Svalbard and Jan Mayen Islands');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SZ', 'Swaziland');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SE', 'Sweden');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'CH', 'Switzerland');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'SY', 'Syrian Arab Republic');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'TW', 'Taiwan');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'TJ', 'Tajikistan');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'TZ', 'Tanzania, United Republic of');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'TH', 'Thailand');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'TG', 'Togo');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'TK', 'Tokelau');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'TO', 'Tonga');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'TT', 'Trinidad and Tobago');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'TN', 'Tunisia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'TR', 'Turkey');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'TM', 'Turkmenistan');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'TC', 'Turks and Caicos Islands');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'TV', 'Tuvalu');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'UG', 'Uganda');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'UA', 'Ukraine');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'AE', 'United Arab Emirates');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'GB', 'United Kingdom');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'US', 'United States');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'UM', 'United States minor outlying islands');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'UY', 'Uruguay');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'UZ', 'Uzbekistan');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'VU', 'Vanuatu');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'VA', 'Vatican City State');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'VE', 'Venezuela');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'VN', 'Vietnam');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'VG', 'Virgin Islands (British)');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'VI', 'Virgin Islands (U.S.)');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'WF', 'Wallis and Futuna Islands');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'EH', 'Western Sahara');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'YE', 'Yemen');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'ZR', 'Zaire');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'ZM', 'Zambia');
INSERT INTO[TimeManagement].[Country] ([CountryCode], [CountryName]) VALUES ( 'ZW', 'Zimbabwe');

END