//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeReg
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderNumber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderNumber()
        {
            this.Projects = new HashSet<Projects>();
        }
    
        public int PK_Id { get; set; }
        public string Number { get; set; }
        public int FK_RequestOrg { get; set; }
        public int FK_Requester { get; set; }
        public int FK_CustomerRef { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projects> Projects { get; set; }
        public virtual CustomerRef CustomerRef { get; set; }
        public virtual Requester Requester { get; set; }
        public virtual RequestOrg RequestOrg { get; set; }
    }
}
