//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeReg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projects()
        {
            this.Comments = new HashSet<Comments>();
            this.TimeRegistration = new HashSet<TimeRegistration>();
            this.UserAssignment = new HashSet<UserAssignment>();
        }
    
        public int PK_Id { get; set; }
        public string Name { get; set; }
        public int FK_OrderNumber { get; set; }
        public int TimeEstimation { get; set; }
        public int FK_ProjectLeader { get; set; }
        public string Scope { get; set; }
        public int FK_TimeType { get; set; }
        public int Status { get; set; }
        public System.DateTime StartingDate { get; set; }
        public string SiteOrVersion { get; set; }
        public int FK_Country { get; set; }
        public int FK_PlatformOrProduct { get; set; }
        public int FK_Turbine { get; set; }
        public int FK_RequestOrg { get; set; }
        public int FK_Requester { get; set; }
        public int FK_CustomerRef { get; set; }
        public string ProjectComment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual Country Country { get; set; }
        public virtual CustomerRef CustomerRef { get; set; }
        public virtual OrderNumber OrderNumber { get; set; }
        public virtual PlatformOrProduct PlatformOrProduct { get; set; }
        public virtual Requester Requester { get; set; }
        public virtual RequestOrg RequestOrg { get; set; }
        public virtual TimeType TimeType { get; set; }
        public virtual Turbine Turbine { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeRegistration> TimeRegistration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAssignment> UserAssignment { get; set; }
    }
}
