//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeReg
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeRegistration
    {
        public int PK_Id { get; set; }
        public int FK_UserId { get; set; }
        public int FK_OrderId { get; set; }
        public int FK_ProjectId { get; set; }
        public int FK_TaskId { get; set; }
        public double Time { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime DateEntry { get; set; }
        public string Comment { get; set; }
    
        public virtual Projects Projects { get; set; }
        public virtual TaskType TaskType { get; set; }
        public virtual Users Users { get; set; }
    }
}
