//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeReg
{
    using System;
    using System.Collections.Generic;
    
    public partial class VI_OrderNumber
    {
        public int PK_Id { get; set; }
        public string Number { get; set; }
        public int FK_RequestOrg { get; set; }
        public string Organization { get; set; }
        public int FK_Requester { get; set; }
        public string RequesterName { get; set; }
        public int FK_CustomerRef { get; set; }
        public string CustomerRefName { get; set; }
        public string Title { get; set; }
    }
}
