//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeReg
{
    using System;
    using System.Collections.Generic;
    
    public partial class VI_Projects
    {
        public int PK_Id { get; set; }
        public string Name { get; set; }
        public int FK_OrderNumber { get; set; }
        public int TimeEstimation { get; set; }
        public Nullable<int> FK_ProjectLeader { get; set; }
        public string UserName { get; set; }
        public string Scope { get; set; }
        public string OrderName { get; set; }
        public Nullable<int> FK_TimeType { get; set; }
        public string TimeTypeName { get; set; }
        public Nullable<int> timeSum { get; set; }
    }
}
