//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeReg
{
    using System;
    using System.Collections.Generic;
    
    public partial class VI_ProjectAndOrderTools
    {
        public string Organization { get; set; }
        public string TimeTypeName { get; set; }
        public string TaskTypeName { get; set; }
        public string CountryName { get; set; }
        public string CustomerRefName { get; set; }
        public string RequesterName { get; set; }
        public string TurbineName { get; set; }
        public string ProductName { get; set; }
    }
}
