//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeReg
{
    using System;
    using System.Collections.Generic;
    
    public partial class VI_TimeRegistration
    {
        public int PK_Id { get; set; }
        public int FK_UserId { get; set; }
        public int FK_ProjectId { get; set; }
        public int FK_TaskId { get; set; }
        public int Time { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime DateEntry { get; set; }
        public string Comment { get; set; }
        public string TaskTypeName { get; set; }
        public string ProjectName { get; set; }
        public string UserName { get; set; }
        public int FK_OrderId { get; set; }
        public string OrderName { get; set; }
    }
}
