//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeReg
{
    using System;
    using System.Collections.Generic;
    
    public partial class VI_UserTimePerProject
    {
        public int PK_Id { get; set; }
        public string UserName { get; set; }
        public string NK_ZId { get; set; }
        public Nullable<double> timeSum { get; set; }
        public int FK_ProjectId { get; set; }
        public System.DateTime Date { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
    }
}
